### ISSUE TITLE
error when displaying results when entering the url wrongly.

### ISSUE THREAD

**Issue by ManuelBot59** [encoreshao/webdata-scraper#1]
error when displaying results when entering the url wrongly.

********************ERROR*****************************
Get Facebook person profile
http://127.0.0.1:5000/facebook/organization/encoreshao

********************CORRECT*****************************
Get Facebook person profile
http://127.0.0.1:5000/facebook/person/encore.shao

**Comment by encoreshao** [comment]
thanks @ManuelQ59!

Yep, you're right! I've update in the README.
